### ISSUE TITLE
Add capital of each state

### ISSUE THREAD

**Issue by ahmad-cod** [bensonarafat/nigeria_states_towns_lgas#4]
You did a nice job, I think it would be better if more data are added, especially the capital of each state.

If you're too busy to do that, I'm willing to help out.

**Comment by bensonarafat** [comment]
@ahmad-cod  
Sure, that will be great, if u can do that it will be amazing. 
Just follow the instructions on the Readme and send the PR.

**Comment by ahmad-cod** [comment]
Okay, I'll do that

**Comment by ahmad-cod** [comment]
I've added capital of each state, and made a pull request.

**Comment by bensonarafat** [comment]
Cool thanks
